---
- hosts: all
  tasks:
  - name: To install chrome driver
    shell: sudo apt-get update && sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4 && sudo apt-get install default-jdk 
  - name: To install chrome driver II
    shell: sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add && sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
  - name: To install chrome driver III
    shell: sudo apt-get -y update && sudo apt-get -y install google-chrome-stable && wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - name: To install chrome driver IV
    shell: unzip chromedriver_linux64.zip && sudo mv chromedriver /usr/bin/chromedriver && sudo chown root:root /usr/bin/chromedriver && sudo chmod +x /usr/bin/chromedriver   
